(** Tests for {!Devkit.Zipx}: good archive round-trip (stored + deflated
    + dirs), ZipSlip refusal, [safe_path] units. Fixtures live in
    [test/fixtures/], generated by the python3 snippet in the Phase 3 plan
    (to regenerate, see AGENTS.md). *)
open Devkit

let with_temp_dir f =
  let dir = Filename.temp_dir "devkit-zipx-" "" in
  let r = f dir in
  let rec rm p =
    if Sys.is_directory p
    then (
      Array.iter (fun e -> rm (Filename.concat p e)) (Sys.readdir p);
      Unix.rmdir p)
    else Sys.remove p
  in
  (try rm dir with
   | _ -> ());
  r
;;

let read_file path =
  let ic = open_in_bin path in
  let n = in_channel_length ic in
  let s = really_input_string ic n in
  close_in ic;
  s
;;

let test_good_zip () =
  with_temp_dir (fun dest ->
    (match Zipx.extract ~zip_path:"fixtures/good.zip" ~dest_dir:dest with
     | Error e -> Alcotest.fail ("extract: " ^ e)
     | Ok () -> ());
    Alcotest.(check string)
      "stored"
      "hello"
      (read_file (Filename.concat dest "hello.txt"));
    Alcotest.(check string)
      "deflated nested"
      "nested-content"
      (read_file (Filename.concat (Filename.concat dest "dir") "nested.txt"));
    Alcotest.(check bool)
      "empty dir"
      true
      (Sys.file_exists (Filename.concat dest "empty-dir")
       && Sys.is_directory (Filename.concat dest "empty-dir")))
;;

let test_evil_zip () =
  with_temp_dir (fun dest ->
    (match Zipx.extract ~zip_path:"fixtures/evil.zip" ~dest_dir:dest with
     | Ok () -> Alcotest.fail "expected ZipSlip refusal"
     | Error e ->
       Alcotest.(check bool)
         "ZipSlip message"
         true
         (Strutil.contains_substring "ZipSlip" e));
    (* Entries before the hostile one are already written (documented);
         nothing escapes the destination. *)
    Alcotest.(check string)
      "prior entry kept"
      "ok"
      (read_file (Filename.concat dest "ok.txt"));
    Alcotest.(check bool)
      "no escape"
      false
      (Sys.file_exists (Filename.concat (Filename.dirname dest) "evil.txt")))
;;

let test_garbage () =
  with_temp_dir (fun dest ->
    match Zipx.extract ~zip_path:"fixtures/does-not-exist.zip" ~dest_dir:dest with
    | Ok () -> Alcotest.fail "expected missing-file error"
    | Error _ -> ());
  match Zipx.list_entries (Bytes.of_string "not a zip at all, far too short!!") with
  | Ok _ -> Alcotest.fail "expected EOCD error"
  | Error _ -> ()
;;

let check_safe name expected =
  match Zipx.safe_path ~dest:"/dest" name with
  | None -> Alcotest.(check bool) name true (expected = None)
  | Some (p, is_dir) ->
    (match expected with
     | None -> Alcotest.fail ("expected refusal: " ^ name)
     | Some (ep, edir) ->
       Alcotest.(check string) (name ^ " path") ep p;
       Alcotest.(check bool) (name ^ " is_dir") edir is_dir)
;;

let test_safe_paths () =
  check_safe "/abs.txt" None;
  check_safe "../evil.txt" None;
  check_safe "a/../../escape.txt" None;
  check_safe {|C:\win.txt|} None;
  check_safe {|..\evil.txt|} None;
  check_safe "" None;
  check_safe "ok.txt" (Some ("/dest" ^ Filename.dir_sep ^ "ok.txt", false));
  check_safe "dir/" (Some ("/dest" ^ Filename.dir_sep ^ "dir", true));
  check_safe
    "a/./b.txt"
    (Some ("/dest" ^ Filename.dir_sep ^ "a" ^ Filename.dir_sep ^ "b.txt", false))
;;

let () =
  Alcotest.run
    "zipx"
    [ "extract", [ Alcotest.test_case "good zip" `Quick test_good_zip ]
    ; "zipslip", [ Alcotest.test_case "evil zip refused" `Quick test_evil_zip ]
    ; "robustness", [ Alcotest.test_case "garbage rejected" `Quick test_garbage ]
    ; "safe_path", [ Alcotest.test_case "units" `Quick test_safe_paths ]
    ]
;;
